# Generated by Django 5.1 on 2024-10-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('moderador', 'Moderador'), ('usuario', 'Usuario')], default='moderador', max_length=20),
        ),
    ]
