# Generated by Django 5.1 on 2024-10-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionterapia',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
