# Generated by Django 5.1 on 2024-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_genero_alter_responsable_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='responsable_apellido',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsable_nombre',
            field=models.CharField(default='aa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsable_parentesco',
            field=models.CharField(default='aa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsable_telefono',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
    ]
