# Generated by Django 5.1 on 2024-10-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_responsable_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='paciente',
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
